### ISSUE TITLE
v0.21 release compiled with wrong JDK version

### ISSUE THREAD

**Issue by nicholastanvis** [jaredtengsw/ip#5]
hello, i'm nicholas and i'm one of the people tasked to evaluate your iP. i just wanted to tell you i'm fully aware that you realised you compiled your iP with java 13 and that is good. unfortunately, i also have to inform you that your most recent release is still compiled with class version 57.0 (which corresponds to java 13), which by right should be class version 55.0 (java 11). hoping you would release another jar file soon, thank you

**Comment by jaredtengsw** [comment]
Hi Nicholas, sorry for the late response and raising this issue. I have just recompiled the files and released a new JAR file (v0.22). Would you mind helping me check again if it works on java 11 now? I would like to make sure that it works fine for someone else other than me.

**Comment by nicholastanvis** [comment]
![image](https://user-images.githubusercontent.com/77217135/111091553-42e2f900-856e-11eb-9ecb-db00ce8fa424.png)
it still uses java 13 and i cannot run the jar file with my java 11

**Comment by jaredtengsw** [comment]
Updated the JAR file once again and @nicholastanvis has helped to validate that it works now on JDK11.

Thank you so much @nicholastanvis, I really appreciate the help given to me!
